# Copyright 2021 LinkedIn Corporation. All rights reserved.
# Licensed under the BSD-2 Clause license.
# See LICENSE in the project root for license information.

name: Build and Publish Docker image
on:
  push:
    # Publish only on `master`
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - 'gobblin-docker/**'
      - '.github/workflows/docker_build_publish.yaml'
  release:
    types: [published, edited]

env:
  IMAGE_NAME: apache/gobblin

jobs:
  build_and_push_to_registry:
    name: Build docker images and publish to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build Docker Tag
        id: build_tag
        run: |
          SHA=`echo ${{ github.sha }} | head -c 7`
          if [[ ${{ github.event_name }} == 'release' ]]; then
            TAG="${{ env.IMAGE_NAME }}:sha-$SHA, ${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}, ${{ env.IMAGE_NAME }}:latest"
          else
            TAG="${{ env.IMAGE_NAME }}:sha-$SHA"
          fi
          echo "tag=$TAG"
          echo "::set-output name=tag::$TAG"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #      - name: Login to GitHub Container Registry
      #        if: github.event_name != 'pull_request'
      #        uses: docker/login-action@v1
      #        with:
      #          registry: ghcr.io
      #          username: ${{ github.repository_owner }}
      #          password: ${{ secrets.CR_PAT }}
      - name: Build Images and Publish
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.build_tag.outputs.tag }}
          push: ${{ github.event_name == 'release' }}
          file: ./gobblin-docker/gobblin/alpine-gobblin-latest/Dockerfile
